var GAME_LEVELS = [
  ["                                                                                 ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                    x                         ",
   "  x                                                    x                         ",
   "  x                                                  o x                         ",
   "  x                                                    x                         ",
   "  x                                                    x                         ",
   "  x                                            o  o    x                         ",
   "  x                                          xxxxxxxxxxx                                   ",
   "  x                                          xxxxxxxxxxx                                   ",
   "  x                                      o   xxxxxxxxxxx                                   ",
   "  x                                     xxx  xxxxxxxxxxx                                      ",
   "  x       o                             xxx  xxxxxxxxxxx                                       ",
   "  x     xxxxx                       o   xxx  xxxxxxxxxxx                                           ",
   "  x     xxxxx        o o           xxx  xxx  xxxxxxxxxxx                                             ",
   "  x     xxxxx       xxxxx          xxx  xxx  xxxxxxxxxxx                                             ",
   "  x  @  xxxxx                      xxx  xxx  xxxxxxxxxxx                                                  ",
   "  xxxxxxxxxxxxxxxxx       xxxxxxx  xxx  xxx  xxxxxxxxxxx                                                                   ",
   "  xxxxxxxxxxxxxxxxx!!!!!!!xxxxxxx!!xxx!!xxx!!xxxxxxxxxxx                                                                       ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                             ",
   "                                                                                 "],
  ["                                                                   ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   " x                                                xxxx!xxxxxxxxxxx ",
   " x                                                xxx!!!xxxxxxxxxx ",
   " x                                                xxx!!!xxxxxxxxxx ",
   " x                                                xxxxvxxxxxxxxxxx ",
   " x                                                xx             x ",
   " x                                                xx             x ",
   " x                                                xx             x ",
   " x                                                xx             x ",
   " x                                                xx             x ",
   " x                                                xx             x ",
   " x                                                xxo      o o o x ",
   " x                                                xxx    xxxxxxxxx ",
   " x                                                xx     xxxxxxxxx ",
   " x                                                xx     xxxxxxxxx ",
   " x                                                xx    oxxxxxxxxx ",
   " x                                                xx    xxxxxxxxxx ",
   " x                                                xx     xxxxxxxxx ",
   " x                                                xx     xxxxxxxxx ",
   " x                                                xxo    xxxxxxxxx ",
   " x                                                xxx    xxxxxxxxx ",
   " x                          o                     xx     xxxxxxxxx ",
   " x                         xxx                    xx     xxxxxxxxx ",
   " x                         xxx                    xx    oxxxxxxxxx ",
   " x                   o     xxx                    xx    xxxxxxxxxx ",
   " x                  xxx    xxx                           xxxxxxxxx ",
   " x                  xxx    xxx                           xxxxxxxxx ",
   " x     @     o      xxx    xxx                o          xxxxxxxxx ",
   " x   xxx   xxxxx    xxx    xxx           xxxxxxxxxxxxxxxxxxxxxxxxx ",
   " x         xxxxx    xxx    xxx     o     xxxxxxxxxxxxxxxxxxxxxxxxx ",
   " x!!!!!!!!!xxxxx    xxx    xxx    xxx    xxxxxxxxxxxxxxxxxxxxxxxxx  ",
   " x!!!!!!!!!xxxxx!!!!xxx!!!!xxx!!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                  "], 
  ["                                                    ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxvxxxxxxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x ",
   " xxxxxxxxxxxxxxxxxxxxvxxxxxxxxxx            o  o  x ",
   " x                      xxxxxxxx          xxxxxxxxx ",
   " x                      xxxxxxxx>     o     <xxxxxx ",
   " x                      xxxxxxxx>     x     <xxxxxx ",
   " x                      xxxxxxxx>           <xxxxxx ",
   " x                      xxxxxxxx> o         <xxxxxx ",
   " x                      xxxxxxxx> x         <xxxxxx ",
   " x             o o      xxxxxxxx>           <xxxxxx ",
   " x          o xxxxx     xxxxxxxx>     o     <xxxxxx ",
   " x          x xxxxx     xxxxxxxx>     x     <xxxxxx ",
   " x            xxxxx    oxxxxxxxx>           <xxxxxx ",
   " x o          xxxxx    xxxxxxxxx>         o <xxxxxx ",
   " xxxxxxxxx    xxxxx     xxxxxxxx>         x <xxxxxx ",
   " xxxxxxxx     xxxxxo    xxxxxxxx>           <xxxxxx ",
   " xxxxxvx     xxxxxxx    xxxxxxxx>     o     <xxxxxx ",
   " xxxx       o xxxxx     xxxxxxxx>     x     <xxxxxx ",
   " x            xxxxx    oxxxxxxxx>           <xxxxxx ",
   " x          x xxxxx    xxxxxxxxx  o          xxxxxx ",
   " x            xxxxx               x          xxxxxx ",
   " x            xxxxx                          xxxxxx ",
   " x @     o    xxxxx                          xxxxxx ",
   " xxxx    x    xxxxxxxxxxxxxxxxxxxx           xxxxxx",
   " xxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxx ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                    "], 
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx!x!x!!!x!x!xxxxxxxxxxxxxxxx",
   "xx!x!x!x!x!x!xxxxxxxxxxxxxxxx",
   "xx!x!x!x!x!x!xxxxxxxxxxxxxxxx",
   "xxx!xx!x!x!x!xxxxxxxxxxxxxxxx",
   "xxx!xx!x!x!x!xxxxxxxxxxxxxxxx",
   "xxx!xx!!!x!!!xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx!!!xxx!x!x!x!x!!xx!xxxxxxxx",
   "x!xxx!xx!x!x!x!x!x!x!xxxxxxxx",
   "!x!x!x!x!x!x!x!x!x!x!xxxxxxxx",
   "!xxxxx!x!x!x!x!x!x!x!xxxxxxxx",
   "!x!x!x!x!x!x!x!x!x!xxxxxxxxxx",
   "!xx!xx!x!!!!!x!x!x!x!xxxxxxxx",
   "x!xxx!xxxxxxxxxxxxxxxxxxxxxxx",
   "xx!!!xxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
